config/routes.rb
Rails.application.routes.draw do
  namespace :admins_ativo do
    resources :admins
    resources :types
    resources :areas
    resources :subareas
    resources :conditions
    resources :situations
    resources :ativos
    resources :vinculos
    resources :users
  end
  namespace :admins_ativo do
    get 'welcome/index'
  end
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'admins_ativo/welcome#index'
end

app/models/ativo.rb
class Ativo < ApplicationRecord
  belongs_to :type
  paginates_per 10


  scope :search, -> (query) { 
    text = "%#{query}%"
    search_columns = %w[tombo description serial]
    where(
      search_columns
        .map { |field| "#{field} LIKE :search" }
        .join(' OR '),
      search: text
    )
  }

end

app/controllers/admins_ativo/admins_controller.rb
class AdminsAtivo::AdminsController < AdminsAtivoController
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
      if @admin.save()
        redirect_to admins_ativo_admins_path, notice: "Novo Administrador criado. Parabéns!"
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @admin.update(params_admin)
      redirect_to admins_ativo_admins_path, notice: "Administrador atualizado. Parabéns!"
    else
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_ativo_admins_path, notice: "Administrador atualizado. Parabéns!"
    else
      render :edit
    end
  end

  private

  def params_admin
    params_admin = params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

end

app/controllers/admins_ativo/areas_controller.rb
class AdminsAtivo::AreasController < AdminsAtivoController
  before_action :set_area, only: [:edit, :update, :destroy]

  def index
    @areas = Area.all.page(params[:page])
  end

  def new
    @area = Area.new
  end

  def create
    @area = Area.new(params_area)
    if @area.save()
      redirect_to admins_ativo_areas_path, notice: "Área criada. Parabéns!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @area.update(params_area)
      redirect_to admins_ativo_areas_path, notice: "Área atualizada. Sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @area.destroy
      redirect_to admins_ativo_areas_path, notice: "Área excluida. Feito!"
    else
      render :index
    end
  end


  private

  def params_area
    params_area = params.require(:area).permit(:description)
  end

  def set_area
    @area = Area.find(params[:id])
  end
end

app/controllers/admins_ativo/ativos_controller.rb
class AdminsAtivo::AtivosController < AdminsAtivoController
  before_action :set_ativo, only: [:show, :edit, :update, :destroy]
  before_action :set_type_options, only: [:new, :create, :edit, :update]

  def index
    if params[:search]
      @ativos = Ativo.includes(:type).search(params[:search]).page(params[:page])
    else
      @ativos = Ativo.includes(:type).page(params[:page])
    end
  end

  def show
    respond_to do |format|
      format.js { render partial: 'admins_ativo/ativos/exibir' }
    end
  end

  def new
    @ativo = Ativo.new
    respond_to do |format|
      format.html
      format.js { render partial: 'admins_ativo/ativos/ativo' }
    end
  end

  def create
    @ativo = Ativo.new(params_ativo)
    if @ativo.save()
      redirect_to admins_ativo_ativos_path, notice: "Ativo criado. Parabéns!"
    else
      render :new
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js { render partial: 'admins_ativo/ativos/ativo' }
    end
  end

  def update
    if @ativo.update(params_ativo)
      redirect_to admins_ativo_ativos_path, notice: "Ativo atualizado. Sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @ativo.destroy
      redirect_to admins_ativo_ativos_path, notice: "Ativo excluido. Feito!"
    else
      render :index
    end
  end

  private

  def params_ativo
    params_ativo = params.require(:ativo).permit(:type_id, :description, :serial, :tombo, :specification, :invoice, :date_acquisition, :warranty, :ata, :bidding)
  end

  def set_ativo
    @ativo = Ativo.find(params[:id])
  end

  def set_type_options
    @type_options = Type.all.pluck(:description, :id)
  end
end

app/controllers/admins_ativo/conditions_controller.rb
class AdminsAtivo::ConditionsController < AdminsAtivoController
  before_action :set_condition, only: [:edit, :update, :destroy]

  def index
    @conditions = Condition.all
  end

  def new
    @condition = Condition.new
  end

  def create
    @condition = Condition.new(params_condition)
    if @condition.save()
      redirect_to admins_ativo_conditions_path, notice: "Condição de Ativo criado. Parabéns!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @condition.update(params_condition)
    if redirect_to admins_ativo_conditions_path, notice: "Condição de Ativo atualizado. Sucesso!"
    else
      render :edit
    end
  end

  def destroy
    @condition.destroy
    if redirect_to admins_ativo_conditions_path, notice: "Condição de Ativo excluida. Feito!"
    else
      render :index
    end
  end

  private

  def params_condition
    params_condition = params.require(:condition).permit(:description)
  end

  def set_condition
    @condition = Condition.find(params[:id])
  end
end

app/controllers/admins_ativo/situations_controller.rb
class AdminsAtivo::SituationsController < AdminsAtivoController
  before_action :set_situation, only: [:edit, :update, :destroy]
  before_action :set_condition_options, only: [:new, :create, :edit, :update]

  def index
    @situations = Situation.includes(:condition)
  end

  def new
    @situation = Situation.new
  end

  def create
    @situation = Situation.new(params_situation)
    if @situation.save()
      redirect_to admins_ativo_situations_path, notice: "Situação de Ativo criado. Parabéns!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @situation.update(params_situation)
      redirect_to admins_ativo_situations_path, notice: "Situação de Ativo atualizada. Parabéns!"
    else
      render :edit
    end
  end

  def destroy
    if @situation.destroy
      redirect_to admins_ativo_situations_path, notice: "Situação de Ativo excluida. Feito!"
    else
      render :index
    end
  end

  private

  def params_situation
    params_situation = params.require(:situation).permit(:condition_id, :description)
  end

  def set_situation
    @situation = Situation.find(params[:id])
  end

  def set_condition_options
    @condition_options = Condition.all.pluck(:description, :id)
  end
end

app/controllers/admins_ativo/subareas_controller.rb
class AdminsAtivo::SubareasController < AdminsAtivoController
  before_action :set_subarea, only: [:edit, :update, :destroy]
  before_action :set_area_options, only: [:new, :create, :edit, :update]

  def index
    @subareas = Subarea.includes(:area).page(params[:page])
  end

  def new
    @subarea = Subarea.new
  end

  def create
    @subarea = Subarea.new(params_subarea)
    if @subarea.save()
      redirect_to admins_ativo_subareas_path, notice: "Área criado. Parabéns!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @subarea.update(params_subarea)
      redirect_to admins_ativo_subareas_path, notice: "Área atualizada. Sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @subarea.destroy
      redirect_to admins_ativo_subareas_path, notice: "Área excluida. Feito!"
    else
      render :index
    end
  end

  private

  def params_subarea
    params_subarea = params.require(:subarea).permit(:area_id, :description )
  end

  def set_subarea
    @subarea = Subarea.find(params[:id])
  end

  def set_area_options
    @area_options = Area.all.pluck(:description, :id)
  end
end

app/controllers/admins_ativo/types_controller.rb
class AdminsAtivo::TypesController < AdminsAtivoController
  before_action :set_type, only: [:edit, :update, :destroy]

  def index
    @types = Type.all.page(params[:page])
  end

  def new
    @type = Type.new
  end

  def create
    @type = Type.new(params_type)
    if @type.save()
      redirect_to admins_ativo_types_path, notice: "Tipo de Ativo criado. Parabéns!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @type.update(params_type)
      redirect_to admins_ativo_types_path, notice: "Tipo de Ativo atualizado. Sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @type.destroy
      redirect_to admins_ativo_types_path, notice: "Tipo de Ativo excluido. Feito!"
    else
      render :index
    end
  end

  private

  def params_type
    params_type = params.require(:type).permit(:description)
  end

  def set_type
    @type = Type.find(params[:id])
  end

end

app/controllers/admins_ativo/users_controller.rb
class AdminsAtivo::UsersController < AdminsAtivoController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save()
      redirect_to admins_ativo_users_path, notice: "Usuário criado. Parabéns!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(params_user)
      redirect_to admins_ativo_users_path, notice: "Usuário atualizado. Sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admins_ativo_users_path, notice: "Usuário excluido. Feito!"
    else
      render :index
    end
  end

  private

  def params_user
    params_user = params.require(:user).permit(:name)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/admins_ativo/vinculos_controller.rb
class AdminsAtivo::VinculosController < AdminsAtivoController
  before_action :set_vinculo, only: [:show, :edit, :update, :destroy]
  before_action :set_user_option, only: [:new, :create, :edit, :update]
  before_action :set_area_option, only: [:new, :create, :edit, :update]
  before_action :set_subarea_option, only: [:new, :create, :edit, :update]
  before_action :set_selects_options, only: [:show, :new, :create, :edit, :update]

  def index
    @vinculos = Vinculo.includes(:user, :area, :subarea)
  end

  def show
    @vinculos = Vinculo.all
  end

  def new
    @vinculo = Vinculo.new
    4.times {@addativos = @vinculo.addativos.build}
  end

  def create
    @vinculo = Vinculo.create(params_vinculo)
    if @vinculo.save()
      redirect_to admins_ativo_vinculos_path, notice: "Vinculo criado. Parabéns!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @vinculo.update(params_vinculo)
      redirect_to admins_ativo_vinculos_path, notice: "Vinculo atualizado. Sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @vinculo.destroy
      redirect_to admins_ativo_vinculos_path, notice: "Vinculo removido. Sucesso!"
    else
      render :index
    end
  end

  private

  def set_vinculo
    @vinculo = Vinculo.find(params[:id])
  end

  def params_vinculo
    params_vinculo = params.require(:vinculo).permit(
    :user_id, 
    :area_id, 
    :subarea_id, 
    :detvinculo,    
    addativos_attributes: [:id, :tombo, :description, :condition, :situation, :_destroy])
  end

  def set_user_option
    @user_option = User.all.pluck(:name, :id)
  end

  def set_area_option
    @area_option = Area.all.pluck(:description, :id)
  end

  def set_subarea_option
    @subarea_option = Subarea.all.pluck(:description, :id)
  end

  def set_selects_options
    @ativos = Ativo.all
    @conditions = Condition.all
    @situations = Situation.all
  end

end

app/controllers/admins_ativo/welcome_controller.rb
class AdminsAtivo::WelcomeController < AdminsAtivoController
  def index
  end
end

app/controllers/admins_ativo_controller.rb
class AdminsAtivoController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_ativo'
end

app/helpers/admins_ativo/admins_helper.rb
module AdminsAtivo::AdminsHelper
end

app/helpers/admins_ativo/areas_helper.rb
module AdminsAtivo::AreasHelper
end

app/helpers/admins_ativo/ativos_helper.rb
module AdminsAtivo::AtivosHelper
end

app/helpers/admins_ativo/conditions_helper.rb
module AdminsAtivo::ConditionsHelper
end

app/helpers/admins_ativo/situations_helper.rb
module AdminsAtivo::SituationsHelper
end

app/helpers/admins_ativo/subareas_helper.rb
module AdminsAtivo::SubareasHelper
end

app/helpers/admins_ativo/types_helper.rb
module AdminsAtivo::TypesHelper
end

app/helpers/admins_ativo/users_helper.rb
module AdminsAtivo::UsersHelper
end

app/views/admins_ativo/ativos/_ativo.js.erb
$("#ativomodal").find(".modal-content").html("<%= j render(:partial => 'admins_ativo/ativos/formmodal', :locals => {:ativo => @ativo }) %>");
$("#ativomodal").modal();

app/views/admins_ativo/ativos/_exibir.js.erb
$("#ativomodal").find(".modal-content").html("<%= j render(:partial => 'admins_ativo/ativos/formshowmodal', :locals => {:ativo => @ativo }) %>");
$("#ativomodal").modal();

app/views/admins_ativo/ativos/_form.html.erb
<% if @ativo.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
            <% @ativo.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>



<%= form_with(model: [ :admins_ativo, @ativo ], local: true ) do |form| %>
<div class="row g-3">
  <div class="form-group col-md-2">
    <%= form.label :type %> <br>
    <%= form.select("type_id", @type_options, {include_blank: 'Selecione...'}, class:"form-control border-6 small") %>
  </div>
  <div class="form-group col-md-10">
    <%= form.label :description %> <br>
    <%= form.text_field :description, class:"form-control border-6 small" %>
  </div>
  <div class="form-group col-md-2">
    <%= form.label :serial %> <br>
    <%= form.text_field :serial, class:"form-control border-6 small" %>
  </div>
  <div class="form-group col-md-2">
    <%= form.label :tombo %> <br>
    <%= form.text_field :tombo, class:"form-control border-6 small" %>
  </div>
  <div class="form-group col-md-8">
    <%= form.label :specification %> <br>
    <%= form.text_area :specification, class:"form-control border-6 small" %>
  </div>
  <div class="form-group col-md-2">
    <%= form.label :invoice %> <br>
    <%= form.text_field :invoice, class:"form-control border-6 small" %>
  </div>
  <div class="form-group col-md-2">
    <%= form.label :date_acquisition %> <br>
    <%= form.date_select :date_acquisition, class:"form-control border-6 small" %>
  </div>
  <div class="form-group col-md-2">
    <%= form.label :warranty %> <br>
    <%= form.text_field :warranty, class:"form-control border-6 small" %>
  </div>
      <div class="form-group col-md-2">
    <%= form.label :ata %> <br>
    <%= form.text_field :ata, class:"form-control border-6 small" %>
  </div>
  <div class="form-group col-md-2">
    <%= form.label :bidding %> <br>
    <%= form.text_field :bidding, class:"form-control border-6 small" %>
  </div>
</div>
<hr/>


<div class="text-right">
  <%= form.submit "Salvar", class:"btn btn-sm btn-primary" %>
  <button class="btn btn-sm btn-danger" data-dismiss="modal">Cancelar</button>
</div>
<% end %>

app/views/admins_ativo/ativos/_formmodal.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="ativomodalLabel">ATIVO</h5>
  </div>
    <div class="modal-body">
      <%= render partial: 'admins_ativo/ativos/form' %>
    </div>
</div>

app/views/admins_ativo/ativos/_formshowmodal.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="ativomodalLabel">DETALHES DO ATIVO</h5>
  </div>
    <div class="modal-body">
      <%= render partial: 'admins_ativo/ativos/show' %>
    </div>
</div>

app/views/admins_ativo/ativos/_formsmodal.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="ativomodalLabel">DETALHES DO ATIVO</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
    <div class="modal-body">
      <%= render partial: 'admins_ativo/ativos/show' %>
    </div>
</div>

app/views/admins_ativo/ativos/_show.html.erb
<form class="row g-3">
  <div class="col-md-3">
    <label for="inputEmail4" class="form-label">type</label>
      <div class="form-control bg-light border-6 smal">
        <%= @ativo.type.description %>
      </div>
  </div>
  <div class="col-md-6">
    <label for="inputPassword4" class="form-label">description</label>
      <div class="form-control bg-light border-6 smal">
        <%= @ativo.description %>
      </div>
  </div>
  <div class="col-md-6">
    <label for="inputCity" class="form-label">specification</label>
      <textarea rows="6" class="form-control bg-light border-6 smal" disabled="disabled">
        <%= @ativo.specification %>
      </textarea>
  </div>
  <div class="col-2">
    <label for="inputAddress" class="form-label">serial</label>
      <div class="form-control bg-light border-6 smal">
        <%= @ativo.serial %>
      </div>
  </div>
  <div class="col-2">
    <label for="inputAddress2" class="form-label">tombo</label>
      <div class="form-control bg-light border-6 smal">
        <%= @ativo.tombo %>
      </div>
  </div>
  <div class="col-md-2">
    <label for="inputZip" class="form-label">invoice</label>
      <div class="form-control bg-light border-6 smal">
        <%= @ativo.invoice %>
      </div>
  </div>
  <div class="col-md-2">
    <label for="inputZip" class="form-label">date_acquisition</label>
      <div class="form-control bg-light border-6 smal">
        <%= @ativo.date_acquisition.strftime("%d/%m/%Y") %>
      </div>
  </div>
  <div class="col-md-2">
    <label for="inputZip" class="form-label">warranty</label>
      <div class="form-control bg-light border-6 smal">
        <%= @ativo.warranty %>
      </div>
  </div>
  <div class="col-md-2">
    <label for="inputZip" class="form-label">ata</label>
      <div class="form-control bg-light border-6 smal">
        <%= @ativo.ata %>
      </div>
  </div>
  <div class="col-md-2">
    <label for="inputZip" class="form-label">bidding</label>
      <div class="form-control bg-light border-6 smal">
        <%= @ativo.bidding %>
      </div>
  </div>
</form>

<hr/>

<div class="text-right">
  <%= link_to 'Editar', edit_admins_ativo_ativo_path(@ativo), 
  remote: true, data: { target: '#ativomodal', toggle: 'modal' }, 
  class:"btn btn-sm btn-primary" %>
  <button class="btn btn-sm btn-danger" data-dismiss="modal">Cancelar</button
</div>

app/views/admins_ativo/ativos/create.js.erb
location.reload();

app/views/admins_ativo/ativos/edit.html.erb
<%= render partial: 'admins_ativo/ativos/form' %>

app/views/admins_ativo/ativos/index.html.erb
<h1>Ativos</h1>    
<!-- Topbar Search -->
<div class="text-right">
  <form class="d-sm-inline-block">
    <div class="input-group">
      <%= form_tag(admins_ativo_users_path, :method => :get) do %>
        <%= text_field_tag 'search', nil, class: "form-control me-2", placeholder: 'Tombo, Serial ou Descrição' %>
      <% end %>
      <%= button_tag type: 'submit', class: "btn btn-primary" do %>
        <i class="fa fa-search"></i>
      <% end %>
    </div>
  </form>
</div>

<br>

<table class="table table-hover">
  <thead>
    <tr>
      <th>type</th>
      <th>description</th>
      <th>serial</th>
      <th>tombo</th>
      <th>
      <th>
      <th>
        <%= link_to new_admins_ativo_ativo_path, remote: true, data: { target: '#ativomodal', toggle: 'modal' } do %>
          <i class="fa fa-plus" style="color:green"></i>
        <% end %> 
      </th>
    </tr>
  </thead>
  <tbody>
    <% @ativos.each do |ativo| %>
      <tr>
        <td><%= ativo.type.description %></td>
        <td><%= ativo.description %></td>
        <td><%= ativo.serial %></td>
        <td><%= ativo.tombo %></td>
        <td style="width: 10px">
          <%= link_to admins_ativo_ativo_path(ativo), remote: true, data: { target: '#ativomodal', toggle: 'modal' } do %>
            <i class="fa fa-eye"></i>
          <% end %>
        <td style="width: 10px">
          <%= link_to edit_admins_ativo_ativo_path(ativo), remote: true, data: { target: '#ativomodal', toggle: 'modal' } do %>
            <i class="fa fa-edit"></i>
          <% end %>
        <td style="width: 10px">
          <%= link_to admins_ativo_ativo_path(ativo), method: :delete, data: {confirm: "Certeza?"} do %>
            <i class="fa fa-trash" style="color:red"></i>
          <% end %>  
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


  <%= paginate @ativos %>

app/views/admins_ativo/ativos/new.html.erb
<%= render partial: 'admins_ativo/ativos/form' %>